parameters:
  database_host: %DB_SERVER
  database_port: ~
  database_name: %DB_NAME
  database_user: %DB_USER
  database_password: %DB_PASSWD
  database_prefix: ps_
  database_engine: InnoDB
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: ~
  mailer_password: ~
  secret: b4IZSYejZIxmjBNXRSdj0
  ps_caching: CacheMemcache
  ps_cache_enable: false
  ps_creation_date: 2016-12-21
  locale: %PS_LANGUAGE-%PS_COUNTRY
  cookie_key: LzKtCvfspUL7LZkJOSGWHK7QuerWVHntXLR3dj4JyD8jxi6xopb0FJGR
  cookie_iv: MqWm7CtF
  new_cookie_key: def000008ba60c1d5a1adc75201a6a0e937fadd3d5ab3d1bc4b0dae57d75904689dd7fa0d1d6f327f4f71495c95d4f2b31391e003af8d9ef32463e71c14baffbc5ca32c2